server:
  port: 80
spring:
  firebase:
    credentials: ${service_json}
  telegram:
    token: ${telegram_token}
azure:
  storage:
    account-name: imagesandwahoo
    container-name: telegram
    connection-string: ${connection_string}