name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Copy .p12 file to resources directory
        run: |
          echo "${{ secrets.SSL_P12_STRING }}" | base64 --decode > src/main/resources/keystore.p12
      - name: Build with Maven
        run: mvn -B -DskipTests=true package --file pom.xml
      - name: Upload application
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "target/maven-0.0.1.jar"
          target: "~/source"

      - name: Start Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd
            sudo kill -9 $(sudo lsof -t -i:443) || true
            sudo nohup java -jar source/target/maven-0.0.1.jar &> /dev/null &
