name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn package

      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 20.187.74.158
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~
            scp target/maven-0.0.1.jar+ azureuser@20.187.74.158:~
            # Kill any running instance of the application
            sudo kill -9 $(sudo lsof -t -i:80) || true
            # Start the newly deployed instance
            sudo nohup java -jar maven-0.0.1.jar+ &> /dev/null &
